### ISSUE TITLE
webview:browse fails silently after first error.

### ISSUE THREAD

**Issue by cbradyatinquire** [NetLogo/webview#1]
try an erroneous call -say, 

webview:browse "google.com"  (forgetting the http://)

we get the error below, and then future calls to webview:browse fail silently.

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.io.IOException: Failed to mail or browse google.com. Error code: -10814
 at sun.lwawt.macosx.CDesktopPeer.lsOpen(CDesktopPeer.java:72)
 at sun.lwawt.macosx.CDesktopPeer.browse(CDesktopPeer.java:65)
 at java.awt.Desktop.browse(Desktop.java:386)
 at org.nlogo.extensions.webview.Browse$.perform(WebViewExtension.scala:239)
 at org.nlogo.prim._extern.perform(_extern.java:55)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:103)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 6.0-PREVIEW-12-15
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_66 (Oracle Corporation; 1.8.0_66-b17)
operating system: Mac OS X 10.9.5 (x86_64 processor)
Scala version 2.11.7
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: GoogleSheetsAnalysis

04:57:37.276 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
04:57:37.275 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
04:57:37.275 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
04:57:37.270 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
04:57:37.210 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:57:37.210 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:57:37.210 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:57:37.210 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:57:37.009 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:57:37.009 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Fixed in https://github.com/NetLogo/webview/releases/tag/v0.7.3
